/**
 * Code Review Agent
 * Scans the repository and produces a structured review report using Claude Opus.
 *
 * Usage:
 *   npm run review              → print report to console
 *   npm run review -- --save   → also save report to REVIEW.md
 */

import { query } from '@anthropic-ai/claude-agent-sdk';
import fs from 'fs';
import path from 'path';

const PROJECT_ROOT = path.resolve(process.cwd());
const SAVE_TO_FILE = process.argv.includes('--save');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'REVIEW.md');

const SYSTEM_PROMPT = `You are a senior full-stack engineer with deep expertise in:
- TypeScript, React (hooks, performance), Node.js, Express
- Security best practices (OWASP Top 10, secrets management)
- REST API design and error handling patterns
- Frontend accessibility and UX

When reviewing code be:
- SPECIFIC: always reference exact file paths and line numbers
- ACTIONABLE: provide concrete fix suggestions, not vague advice
- BALANCED: highlight what is done well, not just problems

Structure your final report using this exact markdown format:

# Code Review Report

## Overall Rating: X/10

## Summary
(2-3 sentence executive summary)

## ✅ Strengths
(bullet list of things done well)

## 🔴 Critical Issues (must fix)
(numbered list; include file:line and suggested fix)

## 🟡 Warnings (should fix)
(numbered list; include file:line and suggested fix)

## 🔵 Suggestions (nice to have)
(numbered list)

## Security Checklist
- [ ] API keys never hardcoded
- [ ] User input validated / sanitised
- [ ] CORS restricted to intended origins
- [ ] Secrets excluded from version control
(mark each ✅ / ❌ based on findings)
`;

const REVIEW_PROMPT = `Perform a thorough code review of this repository.

Steps:
1. First list all source files with Glob to understand the project layout
2. Read every file under src/ and server/ carefully
3. Also check package.json, tsconfig.json, vite.config.ts, and .gitignore
4. Then produce the structured review report described in your system prompt

Pay special attention to:
- Security: API key storage, CORS settings, .gitignore coverage
- TypeScript: proper typing, no unsafe "any", error handling
- React: hook dependencies, memory leaks, unnecessary re-renders
- Node/Express: unhandled promise rejections, proper error middleware
- UX: loading states, error messages, accessibility`;

async function runCodeReview(): Promise<void> {
  console.log('╔══════════════════════════════════════════╗');
  console.log('║        Claude Code Review Agent          ║');
  console.log('║  Model: claude-opus-4-6  (Agent SDK)     ║');
  console.log('╚══════════════════════════════════════════╝\n');
  console.log(`📁 Project: ${PROJECT_ROOT}\n`);
  console.log('⏳ Scanning repository...\n');

  const startTime = Date.now();
  let reportText = '';

  for await (const message of query({
    prompt: REVIEW_PROMPT,
    options: {
      cwd: PROJECT_ROOT,
      allowedTools: ['Read', 'Glob', 'Grep'],
      systemPrompt: SYSTEM_PROMPT,
      model: 'claude-opus-4-6',
      maxTurns: 40,
    },
  })) {
    if ('result' in message) {
      // Final result from the agent
      reportText = message.result ?? '';

      const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
      console.log('\n' + '═'.repeat(50));
      console.log(`✅ Review complete in ${elapsed}s`);
      console.log('═'.repeat(50) + '\n');
      console.log(reportText);

      if (SAVE_TO_FILE) {
        const header = `<!-- Generated by code-review agent on ${new Date().toISOString()} -->\n\n`;
        fs.writeFileSync(OUTPUT_FILE, header + reportText, 'utf-8');
        console.log(`\n💾 Report saved to: ${OUTPUT_FILE}`);
      }
    }
  }

  if (!reportText) {
    console.error('⚠️  Agent returned no result. Check your ANTHROPIC_API_KEY.');
    process.exit(1);
  }
}

runCodeReview().catch((err: unknown) => {
  console.error('Fatal error:', err instanceof Error ? err.message : err);
  process.exit(1);
});
